"""
Django settings for ezbookingtours_store project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
import sys
from dotenv import load_dotenv

# Load enviroment variables (for local)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG") == "True"

# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "seema_rohan",
    "digitalrealty",
    "andrea_scott",
    "driven_mastermind",
    "will_ryan_airport_transfers",
    "store",
    "riviera_maya_airport_transfers",
    "wedding",
    "rohan_karisma",
    "tony_thoa_airport_transfers",
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ezbookingtours_store.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "debug": DEBUG,
        },
    },
]

WSGI_APPLICATION = "ezbookingtours_store.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# Database
# Using PostgreSQL for both production and tests
# Django's test runner automatically creates a separate 'test_<DB_NAME>' database
# This keeps production data completely safe
DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE"),
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation"
        ".UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "es-mx"

TIME_ZONE = "America/Mexico_City"

USE_I18N = True

USE_TZ = True

# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Allow all host headers
ALLOWED_HOSTS = ["*"]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_ROOT = os.path.join(PROJECT_ROOT, "staticfiles")
STATIC_URL = "/static/"

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = [
    os.path.join(PROJECT_ROOT, "static"),
    os.path.join(BASE_DIR, "static"),
]

# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Allow iframing from other websites
X_FRAME_OPTIONS = "ALLOWALL"

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST = os.getenv("EMAIL_HOST")

EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "True") == "True"
EMAIL_CLIENT = os.getenv("EMAIL_CLIENT")

CORS_ALLOW_ALL_ORIGINS = True

# Default email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "Omar Dashboard",
    "SITE_HEADER": "Omar Admin",
    "SITE_SUBHEADER": "Omar Dashboard",
    "SITE_URL": "/",
    "SITE_ICON": lambda request: static("favicon.png"),
    #"SITE_LOGO": lambda request: static("logo.webp"),
    #"SITE_SYMBOL": "directions_car",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/png",
            "href": lambda request: static("favicon.png"),
        },
    ],
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "utils.callbacks.environment_callback",
    "THEME": "light",
    "COLORS": {
        "primary": {
            "50": "oklch(0.97 0.01 255)",
            "100": "oklch(0.92 0.03 255)",
            "200": "oklch(0.85 0.05 255)",
            "300": "oklch(0.75 0.07 255)",
            "400": "oklch(0.65 0.08 255)",
            "500": "oklch(0.48 0.08 255)",
            "600": "oklch(0.40 0.07 255)",
            "700": "oklch(0.32 0.06 255)",
            "800": "oklch(0.25 0.05 255)",
            "900": "oklch(0.18 0.04 255)",
            "950": "oklch(0.12 0.03 255)",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Autenticación"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Usuarios"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Grupos"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _("Tienda"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Tours"),
                        "icon": "map",
                        "link": reverse_lazy("admin:store_tour_changelist"),
                    },
                    {
                        "title": _("Hoteles"),
                        "icon": "hotel",
                        "link": reverse_lazy("admin:store_hotel_changelist"),
                    },
                    {
                        "title": _("Horarios de Tours"),
                        "icon": "schedule",
                        "link": reverse_lazy("admin:store_tourtime_changelist"),
                    },
                    {
                        "title": _("Recogidas"),
                        "icon": "location_on",
                        "link": reverse_lazy("admin:store_pickup_changelist"),
                    },
                    {
                        "title": _("Ventas"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:store_sale_changelist"),
                    },
                ],
            },
            {
                "title": _("Sección de Traslados"),
                "separator": True,
                "items": [],
            },
            {
                "title": _("Riviera Maya"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Transportes"),
                        "icon": "directions_car",
                        "link": reverse_lazy("admin:riviera_maya_airport_transfers_transport_changelist"),
                    },
                    {
                        "title": _("Hoteles"),
                        "icon": "hotel",
                        "link": reverse_lazy("admin:riviera_maya_airport_transfers_hotel_changelist"),
                    },
                    {
                        "title": _("Municipios"),
                        "icon": "location_city",
                        "link": reverse_lazy("admin:riviera_maya_airport_transfers_airbnbmunicipality_changelist"),
                    },
                ],
            },
            {
                "title": _("Will Ryan"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Ventas"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:will_ryan_airport_transfers_sale_changelist"),
                    },
                    {
                        "title": _("Hoteles"),
                        "icon": "hotel",
                        "link": reverse_lazy("admin:will_ryan_airport_transfers_hotel_changelist"),
                    },
                    {
                        "title": _("Transportes"),
                        "icon": "directions_car",
                        "link": reverse_lazy("admin:will_ryan_airport_transfers_transport_changelist"),
                    },
                ],
            },
            {
                "title": _("Tony Thoa"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Ventas"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:tony_thoa_airport_transfers_sale_changelist"),
                    },
                    {
                        "title": _("Hoteles"),
                        "icon": "hotel",
                        "link": reverse_lazy("admin:tony_thoa_airport_transfers_hotel_changelist"),
                    },
                    {
                        "title": _("Transportes"),
                        "icon": "directions_car",
                        "link": reverse_lazy("admin:tony_thoa_airport_transfers_transport_changelist"),
                    },
                    {
                        "title": _("Códigos VIP"),
                        "icon": "vpn_key",
                        "link": reverse_lazy("admin:tony_thoa_airport_transfers_vipcode_changelist"),
                    },
                    {
                        "title": _("Días Gratis"),
                        "icon": "event",
                        "link": reverse_lazy("admin:tony_thoa_airport_transfers_freedays_changelist"),
                    },
                ],
            },
            {
                "title": _("Digital Realty"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Ventas"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:digitalrealty_sale_changelist"),
                    },
                ],
            },
            {
                "title": _("Rohan Karisma"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Ventas"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:rohan_karisma_sale_changelist"),
                    },
                ],
            },
            {
                "title": _("Seema Rohan"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Ventas"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:seema_rohan_sale_changelist"),
                    },
                    {
                        "title": _("Hoteles"),
                        "icon": "hotel",
                        "link": reverse_lazy("admin:seema_rohan_hotel_changelist"),
                    },
                    {
                        "title": _("Transportes"),
                        "icon": "directions_car",
                        "link": reverse_lazy("admin:seema_rohan_transport_changelist"),
                    },
                ],
            },
            {
                "title": _("Andrea Scott"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Ventas"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:andrea_scott_sale_changelist"),
                    },
                ],
            },
            {
                "title": _("Driven Mastermind"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Ventas"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:driven_mastermind_sale_changelist"),
                    },
                ],
            },
            {
                "title": _("Bodas"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Ventas de Bodas"),
                        "icon": "favorite",
                        "link": reverse_lazy("admin:wedding_sale_changelist"),
                    },
                    {
                        "title": _("Códigos VIP"),
                        "icon": "vpn_key",
                        "link": reverse_lazy("admin:wedding_vipcode_changelist"),
                    },
                    {
                        "title": _("Días Gratis"),
                        "icon": "event_available",
                        "link": reverse_lazy("admin:wedding_freedays_changelist"),
                    },
                    {
                        "title": _("Hoteles"),
                        "icon": "hotel",
                        "link": reverse_lazy("admin:wedding_hotel_changelist"),
                    },
                    {
                        "title": _("Transportes"),
                        "icon": "directions_car",
                        "link": reverse_lazy("admin:wedding_transport_changelist"),
                    },
                ],
            },
        ],
    },
}

