# Generated by Django 4.2.7 on 2026-03-23 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seema_rohan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freedays',
            name='category',
        ),
        migrations.DeleteModel(
            name='VipCode',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='vip_code',
        ),
        migrations.DeleteModel(
            name='FreeDays',
        ),
        migrations.DeleteModel(
            name='FreeDaysCategory',
        ),
    ]
