# Generated by Django 4.2.7 on 2026-03-23 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seema_rohan', '0002_remove_freedays_category_delete_vipcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='arriving_airline',
            field=models.CharField(default='', max_length=150, verbose_name='Aerolínea de llegada'),
        ),
        migrations.AddField(
            model_name='sale',
            name='arriving_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de llegada'),
        ),
        migrations.AddField(
            model_name='sale',
            name='arriving_flight',
            field=models.CharField(default='', max_length=150, verbose_name='Vuelo de llegada'),
        ),
        migrations.AddField(
            model_name='sale',
            name='arriving_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de llegada'),
        ),
        migrations.AddField(
            model_name='sale',
            name='departing_airline',
            field=models.CharField(default='', max_length=150, verbose_name='Aerolínea de salida'),
        ),
        migrations.AddField(
            model_name='sale',
            name='departing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de salida'),
        ),
        migrations.AddField(
            model_name='sale',
            name='departing_flight',
            field=models.CharField(default='', max_length=150, verbose_name='Vuelo de salida'),
        ),
        migrations.AddField(
            model_name='sale',
            name='departing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de salida'),
        ),
        migrations.AddField(
            model_name='sale',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seema_rohan.hotel', verbose_name='Hotel'),
        ),
        migrations.AddField(
            model_name='sale',
            name='hotel_name',
            field=models.CharField(default='', max_length=150, verbose_name='Nombre del hotel (Personalizado)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='passengers',
            field=models.IntegerField(default=1, verbose_name='Pasajeros'),
        ),
        migrations.AddField(
            model_name='sale',
            name='transport_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seema_rohan.transport', verbose_name='Tipo de transporte'),
        ),
    ]
