# Generated by Django 4.2.7 on 2026-03-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seema_rohan', '0003_sale_arriving_airline_sale_arriving_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio del transporte', max_digits=10, verbose_name='Precio'),
        ),
    ]
