# Generated by Django 4.2.7 on 2026-03-24 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seema_rohan', '0004_alter_transport_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
    ]
