# Generated by Django 4.2.7 on 2026-03-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seema_rohan', '0005_remove_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='arriving_airline',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Aerolínea de llegada'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='arriving_flight',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Vuelo de llegada'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='departing_airline',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Aerolínea de salida'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='departing_flight',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Vuelo de salida'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='hotel_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre del hotel (Personalizado)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='passengers',
            field=models.IntegerField(blank=True, default=1, verbose_name='Pasajeros'),
        ),
    ]
