# Generated by Django 4.0.4 on 2022-12-16 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_tour_duration_alter_sale_date_alter_tour_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 15, 21, 50, 32, 462407), help_text='Hora de recogida del tour', verbose_name='Hora de recogida'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 21, 50, 32, 462407), help_text='Fecha del tour', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='childs_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de cada niño en el tour (solo si el tour admite niños)', max_digits=10, null=True, verbose_name='Precio Niños'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 21, 50, 32, 353394), help_text='Fecha de fin del tour', verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2022, 12, 15, 21, 50, 32, 353394), help_text='Fecha de inicio del tour', verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='tourtime',
            name='time_start',
            field=models.TimeField(default=datetime.datetime(2022, 12, 15, 21, 50, 32, 461407), help_text='Hora de inicio del tour', verbose_name='Hora de inicio'),
        ),
    ]
