# Generated by Django 4.0.4 on 2022-12-16 06:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_pickup_time_alter_sale_date_alter_tour_childs_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='date',
        ),
        migrations.AddField(
            model_name='sale',
            name='buy_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de inicio de la venta', verbose_name='Fecha de venta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='tour_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 16, 0, 13, 37, 542896), help_text='Fecha del tour', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 12, 16, 0, 13, 37, 541892), help_text='Hora de recogida del tour', verbose_name='Hora de recogida'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2022, 12, 16, 0, 13, 37, 436191), help_text='Fecha de fin del tour', verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2022, 12, 16, 0, 13, 37, 436191), help_text='Fecha de inicio del tour', verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='tourtime',
            name='time_start',
            field=models.TimeField(default=datetime.datetime(2022, 12, 16, 0, 13, 37, 540893), help_text='Hora de inicio del tour', verbose_name='Hora de inicio'),
        ),
    ]
