# Generated by Django 4.0.4 on 2022-12-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_tourtime_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(db_index=True, help_text='Nombre del tour', max_length=160, verbose_name='Nombre'),
        ),
    ]
