# Generated by Django 4.0.4 on 2022-12-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_tour_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
