# Generated by Django 4.0.4 on 2022-12-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_tour_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='id',
            field=models.AutoField(auto_created=True, db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
