# Generated by Django 4.0.4 on 2022-12-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_hotel_options_alter_pickup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(db_index=True, default='Cancun', help_text='Lugar donde se realiza el tour', max_length=150, verbose_name='Lugar'),
        ),
    ]
