# Generated by Django 4.0.4 on 2022-12-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_tour_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='saturnday',
            new_name='saturday',
        ),
    ]
