# Generated by Django 4.0.4 on 2022-12-22 01:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_rename_saturnday_tour_saturday'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tour_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Hora del tour', verbose_name='Hora tour'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id_pick_up',
            field=models.ForeignKey(blank=True, help_text='Tour seleccionado con horario, hotel y pick up', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.pickup', verbose_name='Tour Pick Up'),
        ),
    ]
