# Generated by Django 4.0.4 on 2022-12-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_sale_tour_time_alter_sale_id_pick_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='id_tour',
            field=models.ForeignKey(default=1, help_text='Tour seleccionado', on_delete=django.db.models.deletion.CASCADE, to='store.tour', verbose_name='Tour'),
            preserve_default=False,
        ),
    ]
