# Generated by Django 4.0.4 on 2022-12-24 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_sale_id_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='id_pick_up',
        ),
        migrations.AddField(
            model_name='sale',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Hotel al que pertenece el tour en el horario seleccionado', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.hotel', verbose_name='Hotel'),
        ),
        migrations.AddField(
            model_name='sale',
            name='pick_uo_time',
            field=models.TimeField(blank=True, help_text='Hora de pick up en hotel', null=True, verbose_name='Hora pick up'),
        ),
    ]
