# Generated by Django 4.0.4 on 2022-12-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_remove_sale_id_pick_up_sale_hotel_sale_pick_uo_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='pick_uo_time',
            new_name='pick_up_time',
        ),
    ]
