# Generated by Django 4.0.4 on 2022-12-24 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_rename_pick_uo_time_sale_pick_up_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='adults_num',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='buy_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='childs_num',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='id_tour',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='pick_up_time',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tour_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tour_time',
        ),
    ]
