# Generated by Django 4.0.4 on 2022-12-24 01:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_remove_sale_adults_num_remove_sale_buy_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='adults_num',
            field=models.IntegerField(default=1, help_text='Numero de adultos', verbose_name='Adultos'),
        ),
        migrations.AddField(
            model_name='sale',
            name='buy_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de venta', verbose_name='Fecha venta'),
        ),
        migrations.AddField(
            model_name='sale',
            name='childs_num',
            field=models.IntegerField(default=0, help_text='Numero de niños', verbose_name='Niños'),
        ),
        migrations.AddField(
            model_name='sale',
            name='email',
            field=models.EmailField(db_index=True, default=1, help_text='Email del cliente', max_length=150, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='first_name',
            field=models.CharField(db_index=True, default=1, help_text='Nombre del cliente', max_length=150, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Hotel al que pertenece el tour en el horario seleccionado', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.hotel', verbose_name='Hotel'),
        ),
        migrations.AddField(
            model_name='sale',
            name='id_tour',
            field=models.ForeignKey(default=1, help_text='Tour seleccionado', on_delete=django.db.models.deletion.CASCADE, to='store.tour', verbose_name='Tour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Si el tour esta pagado o no', verbose_name='Pagado'),
        ),
        migrations.AddField(
            model_name='sale',
            name='last_name',
            field=models.CharField(db_index=True, default=1, help_text='Apellido del cliente', max_length=150, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='pick_up_time',
            field=models.TimeField(blank=True, help_text='Hora de pick up en hotel', null=True, verbose_name='Hora pick up'),
        ),
        migrations.AddField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Total de la venta', max_digits=10, verbose_name='Total'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='tour_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha del tour', verbose_name='Fecha tour'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tour_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Hora del tour', verbose_name='Hora tour'),
        ),
    ]
