# Generated by Django 4.0.4 on 2023-08-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('will_ryan_airport_transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='full_data',
            field=models.TextField(default='', verbose_name='Datos completos'),
        ),
    ]
