# Generated by Django 4.0.4 on 2023-08-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('will_ryan_airport_transfers', '0002_alter_sale_full_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
    ]
