# Generated by Django 4.0.4 on 2023-07-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(db_index=True, default='', max_length=150, verbose_name='Apellido')),
                ('sale_datetime', models.DateTimeField(db_index=True, default='', verbose_name='Fecha de venta')),
                ('arriving_price', models.FloatField(default=0.0, verbose_name='Precio de llegada')),
                ('departure_price', models.FloatField(default=0.0, verbose_name='Precio de salida')),
                ('vip_code', models.CharField(db_index=True, default='', max_length=150, verbose_name='Código VIP')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagado')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=150, unique=True, verbose_name='Nombre del ajuste')),
                ('value', models.CharField(db_index=True, default='', max_length=150, verbose_name='Valor del ajuste')),
            ],
            options={
                'verbose_name': 'Ajuste',
                'verbose_name_plural': 'Ajustes',
            },
        ),
        migrations.CreateModel(
            name='VipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, default='', max_length=150, unique=True, verbose_name='Valor')),
                ('enabled', models.BooleanField(default=False, verbose_name='Habilitado')),
            ],
            options={
                'verbose_name': 'Código VIP',
                'verbose_name_plural': 'Códigos VIP',
            },
        ),
    ]
