# Generated by Django 4.0.4 on 2023-07-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(db_index=True, default='', editable=False, max_length=150, unique=True, verbose_name='Nombre del ajuste'),
        ),
    ]
