# Generated by Django 4.0.4 on 2023-07-05 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_alter_settings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de venta'),
        ),
    ]
