# Generated by Django 4.0.4 on 2023-07-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_alter_sale_sale_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='arriving_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='departure_price',
        ),
    ]
