# Generated by Django 4.0.4 on 2023-07-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default='', help_text='Clave del transporte', max_length=150, unique=True, verbose_name='Clave')),
                ('name', models.CharField(db_index=True, default='', help_text='Nombre del transporte', max_length=150, unique=True, verbose_name='Nombre')),
                ('price', models.FloatField(default=0.0, help_text='Precio del transporte', verbose_name='Precio')),
                ('por_defecto', models.BooleanField(default=False, help_text='Transporte por defecto', verbose_name='Por defecto')),
            ],
        ),
    ]
