# Generated by Django 4.0.4 on 2023-07-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0007_transport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
