# Generated by Django 4.0.4 on 2023-07-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0008_rename_settings_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='por_defecto',
            new_name='by_default',
        ),
    ]
