# Generated by Django 4.0.4 on 2023-07-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0009_rename_por_defecto_transport_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='stripe_data',
            field=models.TextField(default='', verbose_name='Datos de Stripe'),
        ),
    ]
