# Generated by Django 4.0.4 on 2023-07-11 01:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0013_alter_sale_stripe_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeDaysCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', help_text='Nombre de la categoría', max_length=150, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria de días gratis',
                'verbose_name_plural': 'Categoria de días gratis',
            },
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': 'Transporte', 'verbose_name_plural': 'Transportes'},
        ),
        migrations.CreateModel(
            name='FreeDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Fecha de día gratis', unique=True, verbose_name='Fecha')),
                ('category', models.ForeignKey(help_text='Categoría de día gratis', on_delete=django.db.models.deletion.CASCADE, to='wedding.freedayscategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Día gratis',
                'verbose_name_plural': 'Días grais',
            },
        ),
    ]
