# Generated by Django 4.0.4 on 2023-07-11 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0014_freedayscategory_alter_transport_options_freedays'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
