# Generated by Django 4.0.4 on 2023-08-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0017_alter_freedays_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sale',
            name='phone',
            field=models.CharField(db_index=True, default='', max_length=150, verbose_name='Teléfono'),
        ),
    ]
