# Generated by Django 4.2.7 on 2026-07-16 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', help_text='Nombre del hotel', max_length=150, unique=True, verbose_name='Nombre')),
                ('extra_price', models.FloatField(default=0.0, help_text='Precio extra por el servicio en este hotel', verbose_name='Precio extra')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, default='', max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(db_index=True, default='', max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('sale_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de venta')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('full_data', models.TextField(default='', verbose_name='Datos completos')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default='', help_text='Clave del transporte', max_length=150, unique=True, verbose_name='Clave')),
                ('name', models.CharField(db_index=True, default='', help_text='Nombre del transporte', max_length=150, unique=True, verbose_name='Nombre')),
                ('price', models.FloatField(default=0.0, help_text='Precio del transporte', verbose_name='Precio')),
                ('por_defecto', models.BooleanField(default=False, help_text='Transporte por defecto', verbose_name='Por defecto')),
            ],
        ),
    ]
