# Generated by Django 4.2.7 on 2026-02-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transport_type', models.CharField(default='', max_length=150, verbose_name='Tipo de transporte')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Correo')),
                ('passengers', models.IntegerField(default=1, verbose_name='Pasajeros')),
                ('price', models.IntegerField(default=0, verbose_name='Precio')),
                ('arriving', models.TextField(default='', verbose_name='Info de Llegada')),
                ('departing', models.TextField(default='', verbose_name='Info de Salida')),
                ('transport_vehicule', models.CharField(default='', max_length=150, verbose_name='Vehiculo de transporte')),
                ('sale_done', models.BooleanField(default=False, verbose_name='Venta realizada')),
            ],
            options={
                'verbose_name': 'Venta (Digital Realty)',
                'verbose_name_plural': 'Ventas (Digital Realty)',
            },
        ),
    ]
