# Generated by Django 4.0.4 on 2024-06-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('passangers', models.IntegerField(default=1, verbose_name='Pasajeros')),
                ('arriving_date', models.DateField(blank=True, null=True, verbose_name='Fecha de llegada')),
                ('arriving_time', models.TimeField(blank=True, null=True, verbose_name='Hora de llegada')),
                ('departing_date', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('departing_time', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('airline', models.CharField(default='', max_length=150, verbose_name='Aerolinea')),
                ('flight_number', models.CharField(default='', max_length=150, verbose_name='Numero de vuelo')),
                ('hotel', models.CharField(default='', max_length=150, verbose_name='Hotel')),
            ],
        ),
    ]
