# Generated by Django 4.0.4 on 2024-06-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rohan_karisma', '0002_remove_sale_airline_remove_sale_arriving_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='passangers',
            new_name='passengers',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='hotel',
        ),
    ]
