# Generated by Django 4.0.4 on 2024-06-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rohan_karisma', '0003_rename_passangers_sale_passengers_remove_sale_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='arriving',
            field=models.TextField(default='', verbose_name='Info de Llegada'),
        ),
        migrations.AddField(
            model_name='sale',
            name='departing',
            field=models.TextField(default='', verbose_name='Info de Salida'),
        ),
    ]
