# Generated by Django 4.2.7 on 2024-08-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rohan_karisma', '0004_sale_arriving_sale_departing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
