# Generated by Django 4.2.7 on 2025-01-22 21:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeDaysCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', help_text='Nombre de la categoría', max_length=150, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoria de días gratis',
                'verbose_name_plural': 'Categoria de días gratis',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=150, unique=True, verbose_name='Nombre del hotel')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio extra')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotel',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(db_index=True, default='', max_length=150, verbose_name='Apellido')),
                ('sale_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de venta')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('vip_code', models.CharField(db_index=True, default='', max_length=150, verbose_name='Código VIP')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('phone', models.CharField(db_index=True, default='', max_length=150, verbose_name='Teléfono')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('stripe_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='Datos de Stripe')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default='', help_text='Clave del transporte', max_length=150, unique=True, verbose_name='Clave')),
                ('name', models.CharField(db_index=True, default='', help_text='Nombre del transporte', max_length=150, unique=True, verbose_name='Nombre')),
                ('price', models.FloatField(default=0.0, help_text='Precio del transporte', verbose_name='Precio')),
                ('by_default', models.BooleanField(default=False, help_text='Transporte por defecto', verbose_name='Por defecto')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
            },
        ),
        migrations.CreateModel(
            name='VipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, default='', max_length=150, unique=True, verbose_name='Valor')),
                ('enabled', models.BooleanField(default=False, verbose_name='Habilitado')),
            ],
            options={
                'verbose_name': 'Código VIP',
                'verbose_name_plural': 'Códigos VIP',
            },
        ),
        migrations.CreateModel(
            name='FreeDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Fecha de día gratis', verbose_name='Fecha')),
                ('category', models.ForeignKey(help_text='Categoría de día gratis', on_delete=django.db.models.deletion.CASCADE, to='tony_thoa_airport_transfers.freedayscategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Día gratis',
                'verbose_name_plural': 'Días gratis',
            },
        ),
    ]
