# Generated by Django 4.2.7 on 2026-02-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driven_mastermind', '0002_alter_sale_arriving_airline_alter_sale_arriving_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='arriving_airline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aerolínea de llegada'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='arriving_flight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vuelo de llegada'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client_first_name',
            field=models.CharField(max_length=255, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client_last_name',
            field=models.CharField(max_length=255, verbose_name='Apellido del cliente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='departing_airline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aerolínea de salida'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='departing_flight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vuelo de salida'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='hotel',
            field=models.CharField(max_length=255, verbose_name='Hotel'),
        ),
    ]
