# Generated by Django 4.0.4 on 2023-05-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirbnbMunicipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AirbnbMunicipality',
                'verbose_name_plural': 'AirbnbMunicipalities',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Nombre del hotel', max_length=150, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Nombre del transporte', max_length=150, verbose_name='Nombre')),
                ('price', models.FloatField(default=0.0, help_text='Precio del transporte', verbose_name='Precio')),
                ('por_defecto', models.BooleanField(default=False, help_text='Transporte por defecto', verbose_name='Por defecto')),
            ],
        ),
    ]
