# Generated by Django 4.0.4 on 2023-05-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviera_maya_airport_transfers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airbnbmunicipality',
            name='extra_price',
            field=models.FloatField(default=0.0, help_text='Precio extra por el servicio en este municipio', verbose_name='Precio extra'),
        ),
        migrations.AddField(
            model_name='airbnbmunicipality',
            name='name',
            field=models.CharField(db_index=True, default='', help_text='Nombre del municipio', max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(db_index=True, default='', help_text='Nombre del hotel', max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.CharField(db_index=True, default='', help_text='Nombre del transporte', max_length=150, verbose_name='Nombre'),
        ),
    ]
