# Generated by Django 4.0.4 on 2023-05-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviera_maya_airport_transfers', '0002_airbnbmunicipality_extra_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='key',
            field=models.CharField(db_index=True, default='', help_text='Clave del transporte', max_length=150, verbose_name='Clave'),
        ),
    ]
