# Generated by Django 4.0.4 on 2023-05-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviera_maya_airport_transfers', '0003_transport_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(db_index=True, default='', help_text='Nombre del hotel', max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='key',
            field=models.CharField(db_index=True, default='', help_text='Clave del transporte', max_length=150, unique=True, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='name',
            field=models.CharField(db_index=True, default='', help_text='Nombre del transporte', max_length=150, unique=True, verbose_name='Nombre'),
        ),
    ]
