# Generated by Django 4.0.4 on 2023-05-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riviera_maya_airport_transfers', '0004_alter_hotel_name_alter_transport_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='extra_price',
            field=models.FloatField(default=0.0, help_text='Precio extra por el servicio en este hotel', verbose_name='Precio extra'),
        ),
    ]
